name: Cypress & Newman E2E Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Instalar dependencias do projeto
        run: npm install

# Sobe a API, valida a rota /clientes, roda o Newman e derruba a API
      - name: Rodar Testes de API (Postman/Newman)
        run: |
          npm install -g newman
          npx start-server-and-test start:backend http://localhost:3000/clientes "newman run postman/Impacta.postman_collection.json -e 'postman/Projeto Impacta.postman_environment.json'"

      # O Cypress assume daqui para testar o Frontend + API juntos
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build --if-present
          start: npm run start:backend, npm run start:frontend
          wait-on: 'http://localhost:5500'
          command: npm run cypress:run