name: Cypress E2E Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Mudamos para a 18.16.0 para evitar o conflito de depreciação do ESM loader
          node-version: 18.16.0

      # A Action oficial instala as dependências do Linux e gerencia os servidores
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build --if-present
          start: npm run start:backend, npm run start:frontend
          # Aguarda o servidor do frontend responder para liberar os testes
          wait-on: 'http://localhost:5500'
          command: npm run cypress:run